### ISSUE TITLE
number_format is applied to exponents in scientific notation

### ISSUE THREAD

**Issue by jacob-long** [hughjonesd/huxtable#37]
I actually think there may be other cases, e.g., with very large numbers or any time R uses scientific notation.

Here's how I came across this. I start with a simple `lm`:

```r
fit <- lm(mpg ~ hp + wt, data = mtcars)
```

And then I center and scale all variables, which will make the intercept term equal to zero.

```r
fit <- jtools::scale_lm(fit)
jtools::summ(fit, digits = 2)
```

```
MODEL INFO:
Observations: 32
Dependent Variable: mpg

MODEL FIT: 
F(2,29) = 69.21, p = 0
R-squared = 0.83
Adj. R-squared = 0.81

Standard errors: OLS 
             Est. S.E. t val. p    
(Intercept)  0    0.08   0    1    
hp          -0.36 0.1   -3.52 0  **
wt          -0.63 0.1   -6.13 0 ***

All continuous variables are mean-centered and scaled by 1 s.d. 
```

Here's what happens with `huxreg` with the default rounding:

```r
print_md(huxreg(fit))
```

```
---------------------------------------------
                               ( 1)          
---------------------- ----------------------
      (Intercept)        5.269e-17.000       
                                             
                            (0.076)          
                                             
          hp                -0.361 **        
                                             
                            (0.103)          
                                             
          wt                -0.630 ***       
                                             
                            (0.103)          
                                             
           N                32               
                                             
          R 2                0.827           
                                             
        logLik              -16.846          
                                             
          AIC               41.693           
                                             
  *** p < 0.001; ** p < 0.01; * p < 0.05.    
---------------------------------------------
```

What is being rounded is the power term in the scientific notation.

**Comment by hughjonesd** [comment]
OK, there are two issues here: first, the intercept is being reported to significant figures rather than to decimal places (and hence is not rounded to zero). Second, the exponent is being displayed as rounded, when it is an integer. The first issue can be changed by altering the number_format of huxreg - I don't know of a better default that would avoid different issues, though you are welcome to suggest one! The second is a genuine bug, so I will change the title to reflect that; here is a test case:

```
tmp <- hux("5e12")
number_format(tmp) <- "%.3f"
tmp
##  5.000e12.000  
```

**Comment by hughjonesd** [comment]
Should be fixed in github, please test

**Comment by jacob-long** [comment]
I just downloaded from Github, this is still present using your brief example code.

**Comment by hughjonesd** [comment]
Oops; didn't work with multi-character exponents. Try now, though I'm a bit worried that this regex may be too tight...
